# docker compose for conduit container 
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build: ./conduit-backend
    restart: unless-stopped
    env_file: ".env"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: 
    context: ./conduit-frontend
    args: 
      API_URL: ${API_URL}
    env_file: ".env"
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8282:80"

volumes:
  pgdata:
